// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageReport } from "./UsageReport";

/**
 * One account's usage, as carried over RPC to clients. `key` matches
 * [`super::claude::account_key`] (or `"codex"`) so a client can pick the focused agent's account.
 */
export type AccountUsage = { key: string, label: string, report: UsageReport, 
/**
 * How long ago the probe captured this, in seconds.
 */
age_secs: number, };
