// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Detected agent choice and probe info for doctor.
 */
export type AgentDoctorInfo = { kind: string, name: string, command: string, detected: boolean, };
