// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentHostSource } from "./AgentHostSource";

/**
 * Machine health and probe info for the Windows ConPTY agent host (`repomon-agent-host.exe`),
 * the Windows counterpart of [`TmuxDoctorInfo`].
 */
export type AgentHostDoctorInfo = { available: boolean, version: string | null, path: string | null, source: AgentHostSource, };
