// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A spawnable agent choice: a built-in kind (detected on PATH) or a configured custom one.
 */
export type AgentChoice = { 
/**
 * The name to pass to `agent.spawn` (a kind like "claude-code", or a custom name).
 */
name: string, 
/**
 * The launch command line.
 */
command: string, 
/**
 * Whether the command's binary was found on PATH.
 */
detected: boolean, 
/**
 * True if user-defined in config (vs a built-in kind).
 */
custom: boolean, 
/**
 * True if this is the configured default agent (preselected in New Lane).
 */
default: boolean, };
