// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an agent is actively working, waiting on the user, idle, or finished.
 */
export type AgentStatus = "running" | "waiting" | "rate-limited" | "idle" | "ended";
