// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A canonical fleet address as accepted on the wire.
 */
export type AgentAddress = string;
