// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentStatus } from "./AgentStatus";
import type { GateVerdict } from "./GateVerdict";
import type { PendingDialog } from "./PendingDialog";

/**
 * A live (or historical) agent session tied to a `(repo, worktree)`.
 */
export type AgentSession = { id: number, agent: string, repo_id: number, worktree_id: number | null, started_at: string, last_activity_at: string, ended_at: string | null, manifest_path: string, tool_call_count: number, title: string | null, 
/**
 * Live status, overlaid by the daemon (not persisted).
 */
status: AgentStatus, 
/**
 * True when detected from a transcript but NOT managed by repomon — i.e. running in
 * another terminal. Overlaid at list time; adopt it to interact from within repomon.
 */
external: boolean, 
/**
 * The agent's session id (Claude transcript id), when known — lets adopt resume this
 * exact session even when several run in the same worktree.
 */
session_id: string | null, 
/**
 * When a rate-limited agent will be auto-continued (UTC). Overlaid by the daemon for the
 * `RateLimited` status; `None` when the reset time couldn't be parsed (periodic retry).
 */
resume_at: string | null, 
/**
 * True when this session was *inferred* from raw worktree file activity rather than detected
 * from a transcript or live process — i.e. repomon can see the worktree is being worked on
 * but can't identify the specific agent (Claude Code worktree-isolated subagents). The UI
 * renders these with a softer "active" indicator and they don't drive "needs you" alerts.
 */
inferred: boolean, 
/**
 * The managed tmux window this session runs in, when repomon manages it. Several agents
 * can run side by side in one lane (one window each); keys/captures/stops are routed to
 * this window. `None` for external and inferred sessions.
 */
tmux_window: string | null, 
/**
 * The agent's most recent message text (truncated) — what it said or asked when it last
 * ended a turn. Gives needs-you notifications their "why".
 */
last_message: string | null, 
/**
 * Set only when the pane is sitting on an interactive dialog (permission prompt, plan
 * approval, option question): the dialog's summary. Clients show approve/menu controls
 * exactly when this is present — a plain end-of-turn `Waiting` has none.
 */
pending_prompt: string | null, 
/**
 * The full parsed dialog behind `pending_prompt` — question, body, options, cursor — so
 * clients can render answer controls without capturing the pane themselves. Overlaid at
 * list time alongside `pending_prompt`; not persisted.
 */
pending_dialog?: PendingDialog | null, 
/**
 * Overlaid when the agent looks stuck: its window/process is alive, no dialog is up, it
 * did not end its turn — and neither the pane nor the transcript has moved for the stall
 * window. A watchdog signal, not a status: `status` still reads Running/Idle underneath.
 */
stale: boolean, 
/**
 * When the stall began (the last time the pane changed), for "stalled 7m" display.
 */
stalled_since?: string | null, 
/**
 * The latest dxkit stop-gate verdict from the worktree's `.dxkit/loop/ledger.jsonl`,
 * when the lane uses dxkit. Overlaid at list time; not persisted. A fresh `allowed`
 * grants done-candidate, a fresh block vetoes it (see `agent_attention_in`).
 */
gate?: GateVerdict | null, 
/**
 * The Claude account (config dir) this agent runs under, overlaid at list time from the
 * transcript. `None` = the default `~/.claude`; `Some` = a variant (`~/.claude-work`). Lets a
 * client attribute account-level usage (the `/usage` probe) to the focused agent. Not persisted.
 */
config_dir: string | null, 
/**
 * A user-set short label for this session, overlaid at list time from the persisted
 * `session_labels` store (keyed by `session_id`). When set, clients show it instead of the
 * auto-derived summary. `None` when unset or when the session has no durable id. Not persisted
 * on the session row itself.
 */
custom_label: string | null, };
