// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A human-confirmed approval rule: routine Bash permission dialogs matching `pattern` in
 * `repo` are auto-approved by the daemon (the always-escalate sniffer still wins).
 */
export type ApprovalRule = { repo: string, pattern: string, created_at: string, };
