// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BrowseEntry } from "./BrowseEntry";

/**
 * A directory listing for the repo browser.
 */
export type BrowseResult = { path: string, parent: string | null, entries: Array<BrowseEntry>, };
