// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in the interactive repo browser (directories only).
 */
export type BrowseEntry = { name: string, path: string, is_repo: boolean, added: boolean, };
