// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a catalog command came from, so the palette can group and namespace it the way the
 * operator's reference does.
 */
export type CatalogSource = "builtin" | "user" | "plugin" | "unknown";
