// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable effort level, as the model panel shows it.
 */
export type CatalogEffort = { id: string, label: string, current: boolean, };
