// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogSource } from "./CatalogSource";

/**
 * One slash command the palette can show, without its leading slash.
 */
export type CatalogCommand = { name: string, 
/**
 * May be empty; never invented when the source does not state one.
 */
description: string, source: CatalogSource, 
/**
 * True when this command can be sent as one fully specified line (its argument included)
 * with no interactive state to steer. False keeps the existing terminal route.
 */
one_shot: boolean, };
