// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogClass } from "./DialogClass";

/**
 * The result of classifying a pending dialog.
 */
export type Classification = { class: DialogClass, repo_scoped: boolean, subject?: string | null, evidence?: Array<string>, };
