// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CatalogCommand } from "./CatalogCommand";
import type { CatalogModel } from "./CatalogModel";

/**
 * The full answer to `agent.command_catalog`. `models` is empty when the kind's model set is
 * not knowable; `model_command` is `None` when this kind has no way to set a model at all.
 */
export type CommandCatalog = { commands: Array<CatalogCommand>, models: Array<CatalogModel>, model_command: string | null, };
