// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single commit, summarized for timelines and the Today view.
 */
export type Commit = { oid: string, repo_id: number, author_name: string, author_email: string, 
/**
 * First line of the commit message.
 */
summary: string, time: string, parent_count: number, };
