// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One commit's full detail, for the `commit.show` RPC: everything a commit-detail view needs to
 * render without a second round trip. `patch`/`stat` mirror `LaneDiff`'s equivalent fields
 * (unified diff text and `git diff --stat` text respectively); capping `patch` to a
 * caller-supplied character limit is the caller's responsibility, same as `diff_patch` above.
 */
export type CommitShow = { 
/**
 * The full 40-char oid, resolved from whatever the caller passed in (which may have been
 * abbreviated) — never the caller's own possibly-short string, so a client always has a
 * stable, unambiguous id to key off of.
 */
oid: string, author_name: string, author_email: string, time: string, 
/**
 * First line of the commit message.
 */
summary: string, 
/**
 * Everything after the summary line (empty string for a subject-only commit message).
 */
body: string, patch: string, stat: string, 
/**
 * Always `false` from [`commit_show`] itself — truncation happens one layer up, in the
 * `commit.show` RPC handler, the same `cap_chars` server-side cap `lane.diff`'s patch uses.
 * Carried as a field here (rather than a separate bool the handler bolts onto a hand-built
 * JSON object, as `lane.diff` does) so `CommitShow`'s ts-rs binding is the RPC's actual wire
 * shape and the frontend gets a real, always-present `boolean` instead of an optional one.
 */
patch_truncated: boolean, };
