// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Carries structured commit details and uncapped patch/stat text for caller-side display limits.
 */
export type CommitShow = { 
/**
 * The full 40-char oid, resolved from whatever the caller passed in (which may have been
 * abbreviated) - never the caller's own possibly-short string, so a client always has a
 * stable, unambiguous id to key off of.
 */
oid: string, author_name: string, author_email: string, time: string, 
/**
 * First line of the commit message.
 */
summary: string, 
/**
 * Everything after the summary line (empty string for a subject-only commit message).
 */
body: string, patch: string, stat: string, 
/**
 * Reports server-side patch truncation; commit_show itself leaves this false.
 */
patch_truncated: boolean, };
