// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A correlation between two repos' active-bucket sets.
 */
export type Correlation = { a: string, b: string, windows: number, overlap: number, };
