// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Parameters for creating a new lane (and its worktree).
 */
export type CreateLaneParams = { repo_id: number, branch: string, source_branch: string | null, path: string | null, copy_files: Array<string>, };
