// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PolicyAction } from "./PolicyAction";
import type { PolicySource } from "./PolicySource";

/**
 * Evaluation outcome for a classified dialog.
 */
export type Decision = { action: PolicyAction, choice?: number | null, source: PolicySource, reason: string, };
