// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable dialog row: its printed number (if any), its label, and an optional
 * description recovered from a run of two or more spaces acting as a column separator.
 */
export type DialogOption = { number?: number | null, text: string, description?: string, };
