// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The filesystem scope of the repository and worktree against which actions are evaluated.
 */
export type DialogScope = { worktree: string, repo_root: string, };
