// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semantic category of a permission dialog.
 */
export type DialogClass = "command_exec" | "file_write" | "network_access" | "credential_access" | "deletion" | "push_remote" | "install" | "device_access" | "unknown";
