// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One selectable dialog row: its printed number (if any) and its text.
 */
export type DialogOption = { number?: number | null, text: string, };
