// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Counts of staged / unstaged / untracked changes in a worktree.
 */
export type DirtyState = { staged: number, unstaged: number, untracked: number, };
