// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The platform `system.doctor` ran on. Clients use this instead of user-agent sniffing to pick
 * platform-correct rows, hints, and install commands.
 */
export type DoctorPlatform = "macos" | "linux" | "windows";
