// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a plugin's enabled/disabled value came from.
 */
export type EnabledSource = "global" | "repo" | "default";
