// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One account the extensions view can target. Keyed the same way as the usage probe
 * (`agent::claude::account_key`) so the two surfaces agree on account identity.
 */
export type ExtAccount = { 
/**
 * Stable key: `"default"` for `~/.claude`, the config-dir path for a variant
 * (e.g. `~/.claude-work`), or `"codex"` for Codex.
 */
key: string, 
/**
 * Short human label: `"main"`, `"work"`, `"codex"`.
 */
label: string, 
/**
 * Whether repomon manages Claude-style extensions (marketplaces/plugins/skills) for this
 * account. False for Codex, which uses a different model, so the UI can show an honest empty
 * state instead of pretending it has Claude plugins.
 */
claude: boolean, };
