// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MarketplaceInfo } from "./MarketplaceInfo";
import type { PluginInfo } from "./PluginInfo";
import type { SkillInfo } from "./SkillInfo";

/**
 * The full extensions snapshot for one scope, returned by `ext.list`.
 */
export type ExtSnapshot = { 
/**
 * None when the `claude` CLI is not on PATH (install/update UI disables).
 */
cli_version: string | null, marketplaces: Array<MarketplaceInfo>, plugins: Array<PluginInfo>, skills: Array<SkillInfo>, };
