// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkippedLane } from "./SkippedLane";

/**
 * Result of fanning a repo-scope change out to lane worktrees.
 */
export type FanoutSummary = { synced_lanes: Array<string>, skipped_lanes: Array<SkippedLane>, };
