// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One entry in a `file.list` directory listing (one worktree level — not a recursive tree, the
 * desktop's file tree expands lazily). `size` is `None` for directories.
 */
export type FileEntry = { name: string, 
/**
 * Relative to the lane's worktree root, forward-slash separated.
 */
path: string, is_dir: boolean, size: number | null, 
/**
 * From a batched `git check-ignore --stdin` over the whole listing (see
 * `repomon-daemon/src/files.rs`), not a per-entry shell-out. `.git` itself is never listed
 * at all (independent of gitignore — see `file.list`'s handler).
 */
ignored: boolean, };
