// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileEntry } from "./FileEntry";

/**
 * `file.list`'s result: one directory level of a lane's worktree.
 */
export type FileListResult = { entries: Array<FileEntry>, 
/**
 * True when the directory had more entries than the cap and the tail was dropped.
 */
truncated: boolean, };
