// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FileSearchHit } from "./FileSearchHit";

/**
 * `file.search`'s result.
 */
export type FileSearchResult = { hits: Array<FileSearchHit>, truncated: boolean, };
