// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `file.read_raw`'s result: base64-encoded file payload plus MIME type and size in bytes.
 */
export type FileReadRawResult = { base64: string, mime: string, size: number, };
