// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `file.write`'s result: enough for the editor to adopt the new on-disk state as its baseline
 * without a round-trip `file.read`.
 */
export type FileWriteResult = { mtime_ms: number, size: number, };
