// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `file.index`'s result: list of all non-ignored relative file paths in the worktree.
 */
export type FileIndexResult = { paths: Array<string>, truncated: boolean, generation: number, };
