// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `file.read`'s result: whole-file content plus enough metadata for the editor's dirty/conflict
 * checks. `mtime_ms` round-trips back into `file.write`'s `expected_mtime_ms`.
 */
export type FileReadResult = { content: string, mtime_ms: number, size: number, 
/**
 * Always `false`: unlike display RPCs (e.g. `lane.diff`'s patch, which caps-and-flags),
 * `file.read` REJECTS a file over its size cap outright rather than truncating it — a
 * truncated read here risks the editor saving the truncated copy back over the real file.
 * Kept for shape symmetry with other file DTOs (and a possible future soft-cap mode); the
 * frontend should not expect this to ever be `true` today.
 */
truncated: boolean, };
