// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `file.diff_base`'s result: the HEAD version of a file in the worktree.
 */
export type FileDiffBaseResult = { content: string | null, kind: "text" | "binary" | "missing", };
