// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * `file.read`'s result: whole-file content plus enough metadata for the editor's dirty/conflict
 * checks. `mtime_ms` round-trips back into `file.write`'s `expected_mtime_ms`.
 */
export type FileReadResult = { content: string, mtime_ms: number, size: number, 
/**
 * Always false because file.read rejects oversized files instead of returning truncated
 * content that an editor could save over the original.
 */
truncated: boolean, kind: string, 
/**
 * `true` when the file size exceeds 2 MiB (large file mode).
 */
large: boolean, };
