// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAddress } from "./AgentAddress";
import type { MessageDeliveryState } from "./MessageDeliveryState";
import type { MessageReadState } from "./MessageReadState";
import type { ResolvedAgentAddress } from "./ResolvedAgentAddress";

/**
 * One durable fleet message.
 */
export type FleetMessage = { id: string, requested_to: AgentAddress, sender: ResolvedAgentAddress, recipient: ResolvedAgentAddress, body: string, thread_id: string, reply_to: string | null, remaining_hops: number, created_at: string, delivered_at: string | null, read_at: string | null, delivery_error: string | null, delivery_state: MessageDeliveryState, read_state: MessageReadState, };
