// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The latest stop-gate verdict for a worktree, as read from the dxkit loop ledger.
 */
export type GateVerdict = { 
/**
 * Whether the gate let the agent stop (`false` = bounced on net-new findings).
 */
allowed: boolean, 
/**
 * Net-new findings that blocked completion (0 when allowed).
 */
net_new_findings: number, 
/**
 * When the gate ran.
 */
at: string, 
/**
 * The Claude session the verdict belongs to, when the hook payload carried one.
 */
session_id?: string | null, };
