// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Machine health and probe info for `git`.
 */
export type GitDoctorInfo = { available: boolean, version: string | null, path: string | null, };
