// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One orchestration-journal row: an orchestrator-initiated action (or a `session_start`
 * marker), what it targeted, and how it went. Params/detail are pre-truncated digests, never
 * full payloads.
 */
export type JournalEntry = { 
/**
 * Rowid; 0 on insert (assigned by the store).
 */
id: number, at: string, 
/**
 * Opaque per-orchestrator-process marker; `session_start` rows carrying it delimit recaps.
 */
session: string, 
/**
 * Tool/action name, e.g. `spawn_agent`, `merge_lane`, `session_start`.
 */
action: string, lane_id: number | null, repo: string | null, 
/**
 * Compact JSON digest of the arguments (truncated at write time).
 */
params: string | null, 
/**
 * `"ok"` or `"error"`.
 */
outcome: string, 
/**
 * Error text or a short result digest (truncated at write time).
 */
detail: string | null, };
