// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Persisted per-lane metadata not derivable from git (pin state, tmux window, agent kind).
 */
export type LaneMeta = { id: number, repo_id: number, worktree_path: string, pinned: boolean, tmux_window: string | null, 
/**
 * The agent kind repomon last spawned in this lane, if any.
 */
agent_kind: string | null, };
