// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentSession } from "./AgentSession";
import type { Repo } from "./Repo";
import type { Worktree } from "./Worktree";
import type { WorktreeState } from "./WorktreeState";

/**
 * The materialized `(repo, worktree, agent?)` join — the UI's primary unit.
 */
export type Lane = { id: number, repo: Repo, worktree: Worktree, state: WorktreeState, 
/**
 * Active sessions only.
 */
agent_sessions: Array<AgentSession>, last_activity_at: string, pinned: boolean, 
/**
 * The lane's role in the fleet. `None` is an ordinary work lane; `"controller"` marks the
 * repomind home lane, whose agents get the full fleet catalog and which cannot be deleted
 * or merged.
 */
role: string | null, };
