// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Delivery mode for agent supervisor nudges / mail.
 */
export type MailDeliveryMode = "nudge" | "full_body";
