// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One configured plugin marketplace.
 */
export type MarketplaceInfo = { name: string, 
/**
 * "github", "url", or "local".
 */
kind: string, 
/**
 * Repo slug, URL, or path.
 */
reference: string, last_updated: string | null, };
