// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FleetMessage } from "./FleetMessage";

/**
 * A newest-first page of durable fleet messages.
 */
export type MessagePage = { messages: Array<FleetMessage>, next_before: string | null, };
