// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The durable delivery state of a fleet message.
 */
export type MessageDeliveryState = "queued" | "delivered" | "failed";
