// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModelRateSource } from "./ModelRateSource";
import type { PriceOverride } from "./PriceOverride";

/**
 * One row of the Settings > Usage "Model rates" table (`usage.models`): a model's resolved
 * rates and where they came from, its raw override if it has one, and how much the ledger has
 * actually seen it, so the table can sort by what matters rather than alphabetically.
 */
export type ModelRateRow = { 
/**
 * The model id or family prefix.
 */
model: string, input_per_mtok: number, output_per_mtok: number, cache_read_per_mtok: number, cache_write_per_mtok: number, source: ModelRateSource, 
/**
 * The raw, possibly-sparse override from `[usage.price_overrides]`, when this model has one.
 * This is the operator's own input, not the resolved row above: a partial override (say,
 * only `output_per_mtok`) still shows only that one field set here, even though the row's
 * other three rates above are filled in from the snapshot or built-in table underneath it.
 */
override: PriceOverride | null, 
/**
 * The most recent ledger event for this model, `None` for a model that only exists because
 * it has an override (an operator naming a family prefix ahead of any usage, per the brief's
 * "Add model" case).
 */
last_seen: string | null, 
/**
 * Tokens (all kinds summed) this model has run in the last 30 days, for sorting the table by
 * what currently matters rather than by raw historical volume.
 */
tokens_30d: number, };
