// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a `usage.models` row's rate resolved from, extending [`RateSource`] with the one case
 * `RateSource` itself never carries: nothing in the table matched at all. `PriceTable::lookup`
 * never returns this; only [`model_rate_rows`] does, for a model the table has no row for.
 */
export type ModelRateSource = "builtin" | "litellm" | "override" | "unpriced";
