// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogOption } from "./DialogOption";

/**
 * A fully parsed interactive dialog: what the agent is asking and the choices it offers.
 * [`detect_dialog`] extracts it from pane text; [`detect_pending_prompt`] remains the
 * compact one-line view for callers that only need the "why".
 */
export type PendingDialog = { 
/**
 * The dialog's box header naming the tool ("Bash command", "Edit file"); `None` for
 * boxless dialogs.
 */
title?: string | null, 
/**
 * The question line ("Do you want to proceed?"). For the folder-trust dialog whose
 * question can scroll out of the capture window, the synthetic "Do you trust this
 * folder?" stands in.
 */
question: string, 
/**
 * Content lines between the header and the question, capped at [`BODY_MAX_LINES`].
 */
body?: Array<string>, 
/**
 * The selectable options, in screen order.
 */
options: Array<DialogOption>, 
/**
 * Index into `options` of the row the selection cursor sits on, if visible.
 */
selected?: number | null, };
