// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A playbook: procedural memory drafted by the orchestrator, inert until a human approves it.
 */
export type Playbook = { name: string, 
/**
 * The live text: draft text before approval, approved text after.
 */
content: string, 
/**
 * `"draft"` or `"approved"`.
 */
status: string, 
/**
 * A pending revision saved over an approved playbook, awaiting re-approval.
 */
draft_content: string | null, created_at: string, updated_at: string, approved_at: string | null, };
