// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EnabledSource } from "./EnabledSource";
import type { PluginProvides } from "./PluginProvides";

/**
 * One Claude Code plugin as seen by the extensions manager.
 */
export type PluginInfo = { 
/**
 * Full id, e.g. "superpowers@claude-plugins-official".
 */
id: string, name: string, marketplace: string, version: string | null, enabled: boolean, enabled_source: EnabledSource, provides: PluginProvides | null, 
/**
 * False when the plugin appears in enabledPlugins but has no install record.
 */
installed: boolean, };
