// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Component counts inside an installed plugin's cache directory.
 */
export type PluginProvides = { skills: number, commands: number, agents: number, };
