// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Origin / rationale for the resolved policy decision.
 */
export type PolicySource = "lane_class" | "global_class" | "approval_rule" | "always_escalate" | "decision_class" | "ambiguous_options" | "not_repo_scoped" | "default";
