// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A `[usage.price_overrides."model"]` entry. Every field is optional: a partial override edits
 * only the rates it names and inherits the rest from the snapshot or built-in row for that model.
 */
export type PriceOverride = { input_per_mtok: number | null, output_per_mtok: number | null, cache_read_per_mtok: number | null, cache_write_per_mtok: number | null, 
/**
 * When the override starts applying. Defaults to the date of the built-in row it replaces,
 * so an undated override supersedes that row rather than sitting behind it in history.
 */
effective_from: string | null, };
