// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One open pull request for the home screen's PR strips, from `gh pr list`. Only produced when
 * `gh` is on PATH; a repo with none, or a missing `gh`, yields no rows rather than an error.
 */
export type PullRequestSummary = { repo_id: number, repo_name: string, 
/**
 * `u32`, not `u64`: ts-rs maps `u64` to a TS `bigint`, which JSON responses never actually
 * carry, and no PR number will approach the `u32` ceiling.
 */
number: number, title: string, url: string, is_draft: boolean, updated_at: string, };
