// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where a resolved rate came from. Config overrides win over a LiteLLM snapshot, which wins over
 * the built-in table — the built-in table is the floor every model can fall back to.
 */
export type RateSource = "builtin" | "litellm" | "override";
