// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RateSourceCounts } from "./RateSourceCounts";

/**
 * What the ledger knows about its price rates: where they came from, how fresh the LiteLLM
 * snapshot is, and whether the last fetch failed. Read by `usage.rates` and printed by
 * `repomon usage rates` and the Usage view's pricing footnote.
 */
export type RatesStatus = { source_counts: RateSourceCounts, 
/**
 * When the cached LiteLLM snapshot was last fetched (a 304 counts as a fetch: it confirmed
 * the cache is current). `None` until the first successful fetch.
 */
fetched_at: string | null, 
/**
 * The cached snapshot's ETag, so a repeat fetch can ask LiteLLM for only what changed.
 */
etag: string | null, 
/**
 * When the daily refresh next runs, given `fetched_at` and the 24h cadence. `None` when
 * refreshing is off or nothing has been fetched yet.
 */
next_refresh_at: string | null, 
/**
 * The last fetch's error, if it failed. Cleared by the next successful fetch.
 */
last_error: string | null, 
/**
 * Whether `[usage] refresh_prices` is on. Off means the counts above are builtin/override
 * only, and `fetched_at`/`next_refresh_at` stay `None`.
 */
enabled: boolean, };
