// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many of the table's priced models come from each source, for the pricing footnote and
 * `usage.rates`.
 */
export type RateSourceCounts = { builtin: number, litellm: number, overrides: number, };
