// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Stores a named revocable device token locally, excluding plaintext tokens from device listings
 * and remote responses while the bridge allowlist enforces authority.
 */
export type RemoteDevice = { name: string, token: string, role: string, created_at: string, last_seen_at: string | null, };
