// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A paired remote-access device: one named, individually-revocable bearer token minted at
 * pairing. `token` is stored plaintext (same threat model as the legacy config-file token) and
 * never crosses the remote bridge or `remote.devices` output. `role` is `"full"` today (the
 * bridge's default-deny allowlist is the real authority); the column exists for future scoping.
 */
export type RemoteDevice = { name: string, token: string, role: string, created_at: string, last_seen_at: string | null, };
