// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepomindBootStatus } from "./RepomindBootStatus";
import type { RepomindCounts } from "./RepomindCounts";
import type { RepomindExportStatus } from "./RepomindExportStatus";

/**
 * The read-only `repomind.status` payload: where the home lives, which lane and window carry
 * the controller, how the one-way export is doing, and what the home holds. Assembled per call
 * and never persisted.
 */
export type RepomindStatus = { 
/**
 * The home repo path, tilde already expanded.
 */
home: string, 
/**
 * Whether it is on disk yet. `repomind.status` never creates anything.
 */
exists: boolean, repo_id?: number | null, lane_id?: number | null, 
/**
 * The controller lane's last recorded tmux window.
 */
window?: string | null, 
/**
 * How many controllers may run in the lane at once (`[repomind] max_controllers`).
 */
max_controllers: number, export: RepomindExportStatus, counts: RepomindCounts, 
/**
 * The assembled boot context: when it was last regenerated, how big it came out, and what
 * the budget forced out of it.
 */
boot: RepomindBootStatus, };
