// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How the daemon's one-way export into the home is doing.
 */
export type RepomindExportStatus = { 
/**
 * When the last export run finished, successfully or not.
 */
last_run?: string | null, 
/**
 * Whether a write is waiting for the debounced run.
 */
pending: boolean, 
/**
 * The last export failure, cleared by the next successful run.
 */
last_error?: string | null, };
