// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the home holds right now, counted from its directories. `README.md` in any of them is
 * the home's own guide, never a plan or a playbook.
 */
export type RepomindCounts = { 
/**
 * Goals in flight: `plans/active/*.md`.
 */
active_plans: number, 
/**
 * Standing orchestrations mirrored from the schedules: `plans/standing/*.md`.
 */
standing: number, 
/**
 * Approved playbooks: `playbooks/*.md`.
 */
playbooks: number, 
/**
 * Drafts awaiting a human: `playbooks/drafts/*.md`.
 */
drafts: number, };
