// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The state of the daemon-owned boot context at `<home>/.repomind/boot.md`, which every
 * controller is handed at spawn. All zero/empty before the first regeneration.
 */
export type RepomindBootStatus = { 
/**
 * When the document was last assembled. `None` until the first spawn or `repomind.boot`.
 */
generated_at: string | null, 
/**
 * Its size in the budget's own units (four characters to a token).
 */
tokens_estimate: number, 
/**
 * Home-relative paths the token budget forced out of the document, least important first.
 */
trimmed: Array<string>, };
