// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentAddress } from "./AgentAddress";

/**
 * A fleet address bound to the identity selected when a message was sent.
 */
export type ResolvedAgentAddress = { address: AgentAddress, lane_id: number | null, slot: number | null, window: string | null, session_id: string | null, agent_kind: string | null, };
