// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A standing-orchestration schedule: a bounded headless repomind run the daemon fires on a
 * spec ("daily 09:00", "every 30m", ...).
 */
export type Schedule = { id: number, spec: string, prompt: string, 
/**
 * The run's action cap — deliberately lower than an attended session's.
 */
max_actions: number, created_at: string, last_run_at: string | null, };
