// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a work session was focused on one repo or spanned several in parallel.
 */
export type SessionKind = "focused" | "parallel";
