// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SkillSource } from "./SkillSource";

/**
 * One standalone skill (SKILL.md directory) as seen by the extensions manager.
 */
export type SkillInfo = { name: string, description: string | null, source: SkillSource, path: string, };
