// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A lane worktree the repo-scope fan-out could not sync.
 */
export type SkippedLane = { lane: string, reason: string, };
