// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogClass } from "./DialogClass";
import type { PolicySource } from "./PolicySource";

/**
 * An audit entry recording an agent supervision event, decision, and outcome.
 */
export type SupervisionEntry = { id: number, at: string, lane_id: number, window: string, session_id?: string | null, agent_kind?: string | null, trigger: string, dialog_class?: DialogClass | null, repo_scoped?: boolean | null, decision: string, policy_source?: PolicySource | null, keys?: Array<string> | null, outcome: string, reason?: string | null, subject?: string | null, pane_excerpt?: string | null, };
