// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogClass } from "./DialogClass";
import type { MailDeliveryMode } from "./MailDeliveryMode";
import type { PolicyAction } from "./PolicyAction";

/**
 * Effective, fully resolved supervision policy used by the daemon loop.
 */
export type SupervisionPolicy = { enabled: boolean, classes: { [key in DialogClass]?: PolicyAction }, mail_mode: MailDeliveryMode, nudge_text: string, stall_mins: number, nudge_retries: number, expect_work: boolean, };
