// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogClass } from "./DialogClass";
import type { MailDeliveryMode } from "./MailDeliveryMode";
import type { PolicyAction } from "./PolicyAction";

/**
 * One lane's stored policy row.
 */
export type SupervisionOverrides = { lane_id: number, enabled: boolean, classes?: { [key in DialogClass]?: PolicyAction }, mail_mode?: MailDeliveryMode | null, nudge_text?: string | null, stall_mins?: number | null, nudge_retries?: number | null, expect_work: boolean, updated_at: string, };
