// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DialogClass } from "./DialogClass";
import type { MailDeliveryMode } from "./MailDeliveryMode";
import type { PolicyAction } from "./PolicyAction";

/**
 * Global defaults for agent supervision.
 */
export type SupervisionConfig = { enabled: boolean, nudge_text: string, mail_mode: MailDeliveryMode, stall_mins: number, nudge_retries: number, classes: { [key in DialogClass]?: PolicyAction }, };
