// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The result of indexing a repo's commits.
 */
export type SyncReport = { repo_id: number, commits_added: number, commits_skipped: number, errors: Array<string>, };
