// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDoctorInfo } from "./AgentDoctorInfo";
import type { AgentHostDoctorInfo } from "./AgentHostDoctorInfo";
import type { DoctorPlatform } from "./DoctorPlatform";
import type { GitDoctorInfo } from "./GitDoctorInfo";
import type { TmuxDoctorInfo } from "./TmuxDoctorInfo";

/**
 * Result of the `system.doctor` machine-health check.
 */
export type SystemDoctorResult = { platform: DoctorPlatform, tmux: TmuxDoctorInfo, git: GitDoctorInfo, 
/**
 * Populated on Windows only; `null` elsewhere, where tmux is the relevant runtime instead.
 */
agent_host: AgentHostDoctorInfo | null, agents: Array<AgentDoctorInfo>, };
