// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AgentDoctorInfo } from "./AgentDoctorInfo";
import type { GitDoctorInfo } from "./GitDoctorInfo";
import type { TmuxDoctorInfo } from "./TmuxDoctorInfo";

/**
 * Result of the `system.doctor` machine-health check.
 */
export type SystemDoctorResult = { tmux: TmuxDoctorInfo, git: GitDoctorInfo, agents: Array<AgentDoctorInfo>, };
