// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A half-open UTC time range `[from, to)`.
 */
export type TimeRange = { from: string, to: string, };
