// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One repo's density row in the timeline.
 */
export type TimelineRow = { repo_id: number, repo_name: string, 
/**
 * Density level (0–5) per time bucket.
 */
density: Array<number>, };
