// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Correlation } from "./Correlation";
import type { TimelineRow } from "./TimelineRow";

/**
 * The full timeline payload: density rows + correlations.
 */
export type TimelineData = { from: string, to: string, bucket_secs: number, rows: Array<TimelineRow>, correlations: Array<Correlation>, };
