// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TmuxDoctorSource } from "./TmuxDoctorSource";

/**
 * Carries tmux probe results for wire compatibility; when not_applicable is true on Windows,
 * clients must omit tmux from dependency rows and health summaries.
 */
export type TmuxDoctorInfo = { available: boolean, version: string | null, source: TmuxDoctorSource | null, path: string | null, 
/**
 * True on Windows, where tmux plays no role. Older clients that don't know this field
 * default it to `false` and keep their pre-Windows behavior.
 */
not_applicable: boolean, };
