// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the detected tmux binary originates.
 */
export type TmuxDoctorSource = "system" | "bundled";
