// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TmuxDoctorSource } from "./TmuxDoctorSource";

/**
 * Machine health and probe info for `tmux`.
 */
export type TmuxDoctorInfo = { available: boolean, version: string | null, source: TmuxDoctorSource | null, path: string | null, };
