// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * State of a tool invocation, shared by pane previews and durable transcript rows.
 */
export type ToolCallStatus = "running" | "ok" | "error";
