// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PendingDialog } from "./PendingDialog";
import type { ToolCallStatus } from "./ToolCallStatus";
import type { TranscriptMail } from "./TranscriptMail";

/**
 * One normalized conversation row. The original role/text/at fields remain readable by legacy
 * history clients; optional fields describe richer transcript rows and live pane previews.
 */
export type TranscriptItem = { 
/**
 * "user" | "assistant" | "tools".
 */
role: string, 
/**
 * Markdown message text, or a readable fallback for tool and status rows.
 */
text: string, 
/**
 * The entry's timestamp, when the transcript records one.
 */
at: string | null, id?: string, mail?: TranscriptMail, 
/**
 * user, assistant, mail, tool_call, dialog, status, or terminal_block.
 */
kind?: string, model?: string, name?: string, input_summary?: string, result_summary?: string, status?: ToolCallStatus, diff?: string, status_kind?: string, cost_usd?: number, partial?: boolean, dialog?: PendingDialog, };
