// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One conversation item from an agent transcript, rendered for clients that lay text out
 * themselves (the mobile chat view): a user or assistant message with the full *unwrapped*
 * text, or an aggregated run of tool calls between messages.
 */
export type TranscriptItem = { 
/**
 * "user" | "assistant" | "tools".
 */
role: string, 
/**
 * Message text, or for "tools" a compact summary ("Bash ×2 · Edit").
 */
text: string, 
/**
 * The entry's timestamp, when the transcript records one.
 */
at: string | null, };
