// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The dimension a summary or timeline splits on.
 */
export type UsageGroupBy = "kind" | "model" | "repo" | "lane" | "account";
