// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Reports manual refresh outcomes, using Cooldown for a concurrent in-flight probe rather than the
 * ordinary freshness interval.
 */
export type UsageRefreshReason = "pending" | "ok" | "probe_disabled" | "no_active_kind" | "cooldown" | "timeout" | "error";
