// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountUsage } from "./AccountUsage";
import type { UsageRefreshedReason } from "./UsageRefreshedReason";

export type UsageRefreshed = { request_id: number, reason: UsageRefreshedReason, detail: string | null, snapshot: Array<AccountUsage>, };
