// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One point on a timeline series.
 */
export type UsagePoint = { at: string, total_tokens: number, cost_usd: number, };
