// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageFindingKind } from "./UsageFindingKind";

/**
 * One plain finding for the optimize panel.
 */
export type UsageFinding = { kind: UsageFindingKind, 
/**
 * What the finding is about: a model id, or a session id.
 */
subject: string, headline: string, detail: string, 
/**
 * The dollars this finding concerns, so the panel can order by what is worth reading.
 */
cost_usd: number, };
