// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageTotals } from "./UsageTotals";

/**
 * One row of a summary breakdown.
 */
export type UsageGroupRow = { 
/**
 * The raw group value: an agent kind, a model id, or a repo or lane id as text.
 */
key: string, 
/**
 * What to show for `key`. Equal to `key` until the daemon resolves repo and lane names.
 */
label: string, totals: UsageTotals, };
