// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageTotals } from "./UsageTotals";

/**
 * One row of `usage.sessions`.
 */
export type UsageSessionRow = { session_id: string, agent_kind: string, 
/**
 * The model the session spent the most tokens on.
 */
model: string, headline: string | null, repo_id: number | null, lane_id: number | null, cwd: string | null, started_at: string | null, ended_at: string | null, turns: number, tool_calls: number, retries: number, totals: UsageTotals, estimated: boolean, external: boolean, };
