// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AccountUsage } from "./AccountUsage";
import type { UsageRefreshReason } from "./UsageRefreshReason";

/**
 * The outcome of a manually-triggered usage refresh, returned by `usage.refresh`.
 */
export type UsageRefreshResult = { 
/**
 * Whether this call's probe round actually refreshed at least one account.
 */
refreshed: boolean, reason: UsageRefreshReason, 
/**
 * A short, human-readable elaboration, set for the non-`ok` reasons that benefit from one.
 */
detail: string | null, 
/**
 * The usage snapshot after the round, same shape as `usage.get`. Present even when
 * `refreshed` is false, so a client can always re-render from the response.
 */
snapshot: Array<AccountUsage>, };
