// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How far one ingest source has been read, and what went wrong last time if anything did.
 */
export type UsageCursor = { source_path: string, 
/**
 * A byte offset for line sources, a millisecond epoch watermark for the OpenCode database.
 */
offset: number, 
/**
 * The source's modification time when it was last read, as a Unix second.
 */
mtime: number, scanned_at: string, error: string | null, 
/**
 * Which revision of the readers produced this source's stored events. A cursor below
 * [`INGEST_VERSION`] is re-read from the start, its previous events replaced.
 */
ingest_version: number, };
