// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A manual probe notification. Detail distinguishes a still-running round from a final timeout.
 */
export type UsageRefreshedReason = "ok" | "probe_disabled" | "no_active_kind" | "timeout" | "error";
