// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One usage limit window, normalized across agents. `pct_used` is how much of the window is
 * consumed (0–100); `label` is a short tag for display (`5h`, `wk`, `mo`, or a model name).
 */
export type UsageWindow = { label: string, pct_used: number, reset_at: string | null, };
