// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageGroupBy } from "./UsageGroupBy";
import type { UsageGroupRow } from "./UsageGroupRow";
import type { UsageTotals } from "./UsageTotals";

/**
 * The answer to `usage.summary`.
 */
export type UsageSummary = { from: string, to: string, group_by: UsageGroupBy, totals: UsageTotals, groups: Array<UsageGroupRow>, 
/**
 * Cached reads as a share of all read-side tokens, between zero and one.
 */
cache_hit_rate: number, 
/**
 * Estimated tokens as a share of all tokens, between zero and one.
 */
estimated_share: number, 
/**
 * Models the price table had no rate for. Their tokens count; their cost reads as zero.
 */
unpriced_models: Array<string>, };
