// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageWindow } from "./UsageWindow";

/**
 * An account's usage: an ordered list of limit windows (shortest first). Empty/absent windows
 * mean nothing was readable — clients show nothing rather than zeros.
 */
export type UsageReport = { windows: Array<UsageWindow>, };
