// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why a manual `usage.refresh` did or did not change anything. A manual request bypasses the
 * probe watcher's five-minute freshness cooldown (it never reports `Cooldown` for that reason);
 * `Cooldown` here instead means a refresh was already in flight when this one arrived, so it was
 * skipped rather than starting a second one.
 */
export type UsageRefreshReason = "ok" | "probe_disabled" | "no_active_kind" | "cooldown" | "timeout" | "error";
