// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsagePoint } from "./UsagePoint";
import type { UsageTotals } from "./UsageTotals";

/**
 * One series of a timeline, one per group.
 */
export type UsageSeries = { key: string, label: string, points: Array<UsagePoint>, totals: UsageTotals, };
