// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Token and cost totals for a set of rows.
 */
export type UsageTotals = { input_tokens: number, output_tokens: number, cache_read_tokens: number, cache_write_tokens: number, thinking_tokens: number, total_tokens: number, 
/**
 * Of `total_tokens`, how many came from an estimate rather than a reported count.
 */
estimated_tokens: number, 
/**
 * Of `total_tokens`, how many a subagent spent rather than the session's own turns.
 */
subagent_tokens: number, cost_usd: number, events: number, };
