// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageCursor } from "./UsageCursor";

/**
 * The answer to `usage.status`.
 */
export type UsageStatus = { 
/**
 * How many sources the ledger tracks.
 */
sources: number, 
/**
 * The most recent scan across all sources.
 */
last_scan_at: string | null, 
/**
 * Only the sources that failed, so a healthy ledger sends an empty list.
 */
errors: Array<UsageCursor>, events: number, first_event_at: string | null, last_event_at: string | null, 
/**
 * Whether an ingest pass is running right now.
 */
ingesting: boolean, 
/**
 * Sources an older reader wrote that ingest has yet to re-read. Counts down to zero over a
 * few passes after a reader is corrected.
 */
stale_sources: number, };
