// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What kind of thing the optimize panel found.
 */
export type UsageFindingKind = "cost_driver" | "cache_miss" | "retries" | "model_choice";
