// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UsageBucket } from "./UsageBucket";
import type { UsageGroupBy } from "./UsageGroupBy";
import type { UsageSeries } from "./UsageSeries";

/**
 * The answer to `usage.timeline`.
 */
export type UsageTimeline = { bucket: UsageBucket, group_by: UsageGroupBy, series: Array<UsageSeries>, 
/**
 * Every bucket start any series has a point in, oldest first, so a chart can share an axis.
 */
buckets: Array<string>, };
