// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A manual probe notification. Timeout means the round is still running.
 */
export type UsageRefreshedReason = "ok" | "timeout" | "error";
