// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A single worktree of a repo (the main checkout is also a worktree).
 */
export type Worktree = { id: number, repo_id: number, path: string, 
/**
 * `None` when HEAD is detached.
 */
branch: string | null, head: string, is_main: boolean, 
/**
 * Last path component — what the UI shows.
 */
name: string, };
