// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { SessionKind } from "./SessionKind";

/**
 * A detected window of activity (Phase 3).
 */
export type WorkSession = { from: string, to: string, kind: SessionKind, repo_ids: Array<number>, repo_names: Array<string>, commit_count: number, };
