// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DirtyState } from "./DirtyState";

/**
 * The live git state of a worktree - the part that changes as work happens.
 */
export type WorktreeState = { worktree_id: number, head: string, branch: string | null, upstream: string | null, ahead: number, behind: number, dirty: DirtyState, last_commit_at: string | null, locked: boolean, prunable: boolean, 
/**
 * Carries the newest changed-file mtime as a live, unpersisted activity signal, absent for
 * clean worktrees.
 */
last_change_at: string | null, 
/**
 * Marks non-default attached branches already contained in the default branch, computed live
 * and omitted when false.
 */
merged?: boolean, };
