# Link the Windows CRT statically so executables run without a redistributable. Always pass an
# explicit --target x86_64-pc-windows-msvc so these target flags do not reach host build scripts or
# proc-macro dylibs.
[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]

[target.aarch64-pc-windows-msvc]
rustflags = ["-C", "target-feature=+crt-static"]
