#!/usr/bin/env bash
# Makes every worktree (lane) under a repo's lanes root share one Cargo build
# directory, instead of each carrying its own 20-28 GB target/. See
# docs/shared-cargo-target.md for the full design and the escape hatch.
#
# How: writes .cargo/config.toml one level ABOVE every lane, in the lanes
# root itself (e.g. ~/code/repomon-wt/.cargo/config.toml). That directory is
# not a git worktree and is never a lane's own directory, so it can never be
# deleted by removing a lane. Cargo walks the directory tree from its current
# working directory up to the filesystem root collecting every .cargo/config.toml
# it passes and merges them, so this single generated file is picked up by
# `cargo` run from inside ANY lane under this root - whether that invocation
# comes from the daemon spawning an agent, or the operator typing `cargo test`
# by hand - with no per-lane setup, no env var, and no daemon code involved.
# A lane's own tracked .cargo/config.toml (if any) is closer to the crate root
# and wins on any key it also sets, which is how the per-lane opt-out works
# (see docs/shared-cargo-target.md).
#
# Safe to re-run: fully idempotent, only ever rewrites the one generated file.
#
# Usage:
#   scripts/setup-shared-cargo-target.sh [lanes-root]
#
#   lanes-root defaults to ~/code/<this-repo>-wt, Repomon's default
#   worktree_root_template ("~/code/{repo}-wt/{branch}"). Pass it explicitly
#   if this repo's worktree_root_template was customized away from the
#   default (see `worktree_root_template` in Repomon's config).
#
# Env:
#   REPOMON_CARGO_TARGET_ROOT   Where shared target dirs live, one subdir per
#                               repo. Defaults to a platform cache dir.
set -euo pipefail

script_dir="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
repo_root="$(cd "$script_dir/.." && pwd)"

# The repo's name, not this worktree's directory name (a lane's checkout is named after its
# branch, e.g. "chore-shared-cargo-target", not the repo). The git-common-dir is shared by
# every worktree of a repo and lives inside the main checkout, so its parent's basename is the
# repo name regardless of which lane this script runs from.
common_dir="$(git -C "$repo_root" rev-parse --path-format=absolute --git-common-dir 2>/dev/null)" || {
    echo "error: $repo_root is not a git repository" >&2
    exit 1
}
repo_name="$(basename "$(dirname "$common_dir")")"

default_lanes_root="$HOME/code/${repo_name}-wt"
lanes_root="${1:-$default_lanes_root}"

if [ ! -d "$lanes_root" ]; then
    echo "error: lanes root does not exist: $lanes_root" >&2
    echo "  pass it explicitly if worktree_root_template is not the default (~/code/{repo}-wt/{branch})" >&2
    exit 1
fi
lanes_root="$(cd "$lanes_root" && pwd)"

case "$(uname -s)" in
    Darwin) default_cache_root="$HOME/Library/Caches/repomon-cargo-target" ;;
    *) default_cache_root="${XDG_CACHE_HOME:-$HOME/.cache}/repomon-cargo-target" ;;
esac
cache_root="${REPOMON_CARGO_TARGET_ROOT:-$default_cache_root}"

lanes_root_name="$(basename "$lanes_root")"
key="${lanes_root_name%-wt}"
target_dir="$cache_root/$key"

mkdir -p "$target_dir"
mkdir -p "$lanes_root/.cargo"
config_file="$lanes_root/.cargo/config.toml"

cat >"$config_file" <<EOF
# Generated by scripts/setup-shared-cargo-target.sh in the $repo_name repo.
# Do not hand-edit; re-run that script to regenerate. Safe to delete to fall
# back to one target/ per lane again.
[build]
target-dir = "$target_dir"
EOF

echo "shared cargo target dir for '$key': $target_dir"
echo "ancestor config written: $config_file"
echo "every lane under $lanes_root now shares that target dir on its next cargo invocation"
